[package]
name = "set-cosmic-theme"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
cosmic-theme = { git = "https://github.com/pop-os/libcosmic" }
cosmic-config = { git = "https://github.com/pop-os/libcosmic", default-features = false }
ron = "0.8.1"
